### PR TITLE
Add certificate verification

### PR DESCRIPTION
**Pull request by janoszen**
This change adds proper certificate verification for the oVirt engine. It is still untested, hence the WIP.

### CODE REVIEW

**Comment by janoszen** [comment]
@Gal-Zaidman your thoughts?

**Comment by Gal-Zaidman** [comment]
Looks good to me, but please also edit the readme.
https://github.com/oVirt/terraform-provider-ovirt#provider-usage

@emesika @sandrobonazzola 
Notice that this change will break current users scripts.
I saw that in the past this repo used tags and releases, maybe we should add a release before and after this change with a warning, or an email to ovirt users informing them about the change

**Comment by janoszen** [comment]
@Gal-Zaidman ack, will do that, and I'll run some manual tests too.

**Comment by michalskrivanek** [comment]
> Notice that this change will break current users scripts.

but it's not going to break OCP installer, right?

**Comment by janoszen** [comment]
@michalskrivanek separate patches are on their way for the installer.

**Comment by janoszen** [comment]
Update: ran tests with both `OVIRT_INSECURE` and `OVIRT_CAFILE`, both worked:

```
make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtDataCenter_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtDataCenter_ -timeout 180m
=== RUN   TestAccOvirtDataCenter_basic
--- PASS: TestAccOvirtDataCenter_basic (7.02s)
PASS
ok      github.com/ovirt/terraform-provider-ovirt/ovirt 7.026s
```

We can go ahead and plan releasing this. **This is a breaking change!**

**Comment by emesika** [comment]
I checked OCP installer on top of this patch and it runs OK

**Comment by janoszen** [comment]
@emesika then something is wrong, this patch is incompatible with the current installer codebase.

**Pull request merged**
