### PR TITLE
Rename mentions of repo name from imjoey to ovirt

### PR DESCRIPTION
**Pull request by rgolangh**
@imjoey @sandrobonazzola please review

### CODE REVIEW

**Comment by imjoey** [comment]
@rgolangh Is this PR only rename the mentions in readme, or shall we also rename all of them in some other places? What's your opinion?

**Comment by rgolangh** [comment]
> @rgolangh Is this PR only rename the mentions in readme, or shall we also rename all of them in some other places? What's your opinion?

You are right - I'll run a deeper 'grep' :) and repost

**Comment by imjoey** [comment]
@rgolangh There is one more `imjoey` in https://github.com/oVirt/terraform-provider-ovirt/blob/7613d73f99ad5d56383a33a996bef0b3347ccd2d/scripts/changelog-links.sh#L27 。 😄

**Comment by imjoey** [comment]
@rgolangh  Your updates looks good to me, thanks. I also fix the CI errors due to the uppercase `oVirt` after renaming. I think we should fix it in this PR to keep continuous CI success.  @rgolangh @sandrobonazzola  Please review it for me. Thanks

**Comment by imjoey** [comment]
> @rgolangh Your updates looks good to me, thanks. I also fix the CI errors due to the uppercase `oVirt` after renaming. I think we should fix it in this PR to keep continuous CI success. @rgolangh @sandrobonazzola Could you please review it for me. Thanks

Since the commits are all specific and clear, I would merge it. Please let me know if anything is not OK. :)

**Pull request merged**
