### PR TITLE
Add OST tests to terraform provider.

### PR DESCRIPTION
**Pull request by eyonasi**
Signed-off-by: Ehud Yonasi <eyonasi@redhat.com>

Fixes #0000

Changes proposed in this pull request:

* Change 1
* Change 2

Output from acceptance testing:

```
$ make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtDataCenter_'

...
```

### CODE REVIEW

**Comment by Gal-Zaidman** [comment]
I think this needs a rebase :)

**Comment by janoszen** [comment]
This does need a rebase, and we should work together on my test refactoring

**Comment by eyonasi** [comment]
I will fix it to fetch the OST patch commit as it is not merged yet: https://gerrit.ovirt.org/#/c/ovirt-system-tests/+/112600/
But after that the code needs to be the same. WDYT?

**Comment by janoszen** [comment]
@eyonasi how is this going to work specifically? We have a test battery WIP that can run against any oVirt cluster that has at least one host here: https://github.com/oVirt/terraform-provider-ovirt/pull/267 This will run by setting a few env variables and then running `go test`.

**Comment by emesika** [comment]
please rebase and resolve conflicts

**Comment by eyonasi** [comment]
Closing as of duplicate of: https://github.com/oVirt/terraform-provider-ovirt/pull/285

**Pull request closed without merging**
