### PR TITLE
Testing update

### PR DESCRIPTION
**Pull request by jake2184**
Fixes 1) of  #132 

Changes proposed in this pull request:

A general overhaul/update of the testing framework

* Remove hard-coded resource IDs
* Fixed some broken/outdated tests
* Make tests ParallelTests to drastically reduce runtime

I've added TESTING.md for a guide on testing (I had to work out a lot via reverse engineering).

There are still some outstanding issues with external resources (like an NFS server) and some static IPs for external resources/VMs, but now I have the majority of tests passing on a clean local oVirt engine/host. 

Part 2) of #132 still needs implementing, but that probably revolves spinning up a fresh ovirt engine and host container to test against.

### CODE REVIEW

**Comment by jake2184** [comment]
Rebased on master

**Review by emesika — COMMENTED** [review]
Please fix trailing white space errors 

error: 195 lines add whitespace errors.

**Comment by jake2184** [comment]
Hi,

I'm aware this PR needs a bit more work - I now have a better setup to test against. I would also like to incorporate tests for other outstanding PRs, so please consider this on hold until those have been reviewed.

**Comment by emesika** [comment]
@jake2184 

Any news with this patch ?

**Comment by jake2184** [comment]
I've hit a bit of a crunch point with my work, so I would expect this to not be complete for a month or two. I would also want to wait until my other PRs are resolved first.

I'm happy to mark this PR on hold, or even close it, if needed.

**Comment by janoszen** [comment]
Hello @jake2184 FYI we are working on getting oVirt containerized for testing purposes (see [this project](https://github.com/janoszen/ovirt-in-a-box)). If we can get this running this should help greatly with testing.

**Comment by jake2184** [comment]
OK, thanks. Happy to close this PR as I'm not going to work on it soon as I think I have most of the functionality I now require - Still have other outstanding PRs though

**Comment by janoszen** [comment]
Thanks for the feedback @jake2184 we are working to get through the PR's, but we need to set up a proper testing infrastructure first.

**Pull request closed without merging**
