### PR TITLE
Fixes #345: introduce data-source for hosts in cluster

### LINKED ISSUE #345: Implement the `ovirt_cluster_hosts` data source
## Please describe what you would like to see

We need to be able to list all hosts in a cluster.

## Please describe the solution you'd like

We need a data source that is as follows:

```terraform
data "ovirt_cluster_hosts" "master" {
  cluster_id = var.cluster_id
}
```

The returned list should contain at least the `id` field but may also include all additional fields from the `Host` object in the go-ovirt-client.

## Please describe your use case

We need to pin the VMs to the existing hosts in Terraform when desired in the OCP installer. See openshift/installer#5867 for details.

### PR DESCRIPTION
**Pull request by eslutsky**
## Please describe the change you are making

This PR fixes https://github.com/oVirt/terraform-provider-ovirt/issues/345 and adds the ability to list hosts by cluster ID.

## Are you the owner of the code you are sending in, or do you have permission of the owner?

Yes

## The code will be published under the BSD 3 clause license. Have you read and understood this license?

Yes

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically. ( keep in mind this list might be overwritten if the job XML is refreshed, for permanent whitelisting, please follow #3 option )
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Review by janosdebugs — CHANGES_REQUESTED** [review]
Actually, could you add examples to the examples directory?

**Review by janosdebugs — APPROVED** [review]

**Review by janosdebugs — CHANGES_REQUESTED** [review]
@eslutsky you merged instead of a rebase. Could you rebase please?

**Comment by eslutsky** [comment]
> 



> @eslutsky you merged instead of a rebase. Could you rebase please?

done

**Review by janosdebugs — APPROVED** [review]

**Review by janosdebugs — APPROVED** [review]

**Review by janosdebugs — APPROVED** [review]

**Pull request merged**
