### PR TITLE
Bug 2035334: Preallocated disks for OCP nodes

### PR DESCRIPTION
**Pull request by janosdebugs**
## Please describe the change you are making

This change adds utilities needed for [RFE 2035334](https://bugzilla.redhat.com/show_bug.cgi?id=2035334), which enables provisioning OCP nodes with preallocated disks.

## Are you the owner of the code you are sending in, or do you have permission of the owner?

Yes

## The code will be published under the BSD 3 clause license. Have you read and understood this license?

Yes

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by mykaul** [comment]
I remember having a past discussion in which we discussed if customers are able to make the right decision on sparseness. The thought was that on block (FC, iSCSI) it probably should never be sparse, and on file, it'll always be - and therefore no point in exposing it. Unsure what the UI in oVirt or the API does today, if at all.

**Comment by janosdebugs** [comment]
> I remember having a past discussion in which we discussed if customers are able to make the right decision on sparseness. The thought was that on block (FC, iSCSI) it probably should never be sparse, and on file, it'll always be - and therefore no point in exposing it. Unsure what the UI in oVirt or the API does today, if at all.

@mykaul the API exposes these flags, but the UI doesn't seem to:

Screenshot_20220216_094426

I will investigate what the UI maps to.

**Comment by ahadas** [comment]
> I remember having a past discussion in which we discussed if customers are able to make the right decision on sparseness. The thought was that on block (FC, iSCSI) it probably should never be sparse, and on file, it'll always be - and therefore no point in exposing it. Unsure what the UI in oVirt or the API does today, if at all.

Yeah, that's the logic we used to have in the webadmin
That has changed in 4.3 due to [bz 1615287](https://bugzilla.redhat.com/show_bug.cgi?id=1615287) that requested the ability to provision preallocated volumes on file storage - so [raw volumes are still preallocated on block storage](https://github.com/oVirt/ovirt-engine/blob/ovirt-engine-4.4.10.6/frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/dataprovider/AsyncDataProvider.java#L1142) but when it comes to file storage, the allocation type of raw volumes [is determined by the allocation type of the corresponding template volumes](https://github.com/oVirt/ovirt-engine/blob/ovirt-engine-4.4.10.6/frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/dataprovider/AsyncDataProvider.java#L1134-L1141)

**Comment by janosdebugs** [comment]
@michalskrivanek suggested that we should expose all the flags and create appropriate documentation for it. This is better since we create an unopinionated exposure of these features instead of an opinionated set of options which may turn out to be wrong and difficult to reverse.

**Comment by mykaul** [comment]
> @michalskrivanek suggested that we should expose all the flags and create appropriate documentation for it. This is better since we create an unopinionated exposure of these features instead of an opinionated set of options which may turn out to be wrong and difficult to reverse.

ACK - but what will be the defaults?

**Comment by michalskrivanek** [comment]
I think we have 2 choices/changes to make. VM from Template linking, and disk format.

It makes sense to always "clone" the template. That is aligned with UI (we default to "clone" for "server" type VMs, the same ones we use in OCP. It's unintended difference in OCPonRHV API usage). IMHO no need to expose a configuration option for this. If anything we can respect the VM's type which in case of IPI will always mean "clone", but would allow people to override it with custom RHCOS template set as Desktop. 

For disk format it's a bit ore questionable. I think it still makes sense to overcommit in many cases, and it's a question whether that is going to cause any problems once we improve the thin provisioning thresholds in bug https://bugzilla.redhat.com/show_bug.cgi?id=2051997. Still or performance reasons it may make sense to use "raw". I'd lean towards making it a default, but it needs to be configurable.

**Comment by janosdebugs** [comment]
@michalskrivanek there are actually two defaults to be discussed, but those should be done on openshift/installer#5594 and not here.

Default 1: the default value when a *new* install config is created.
Default 2: the default that is applied when an old install config is imported.

Again, please head over to openshift/installer#5594 to discuss.

**Comment by janosdebugs** [comment]
@eslutsky review please

**Review by eslutsky — APPROVED** [review]

**Comment by janosdebugs** [comment]
@sandrobonazzola can you please override CI?

**Comment by ovirt-infra** [comment]
Some tests failed

**Comment by ovirt-infra** [comment]
Some tests failed

**Comment by ovirt-infra** [comment]
Some tests failed

**Pull request merged**
