### PR TITLE
Uninstall renovate-bot integration

### PR DESCRIPTION
**Pull request by imjoey**
Signed-off-by: imjoey <majunjiev@gmail.com>

In accordance to the discussions in #151 , we decide to remove the integration with renovate-bot which deal with the update of deps automatically. We believe a fine-grained control on updating deps will always keep the project stable, simple and production-ready.

Changes proposed in this pull request:

* Remove the configuration files of renovate-bot

### CODE REVIEW

**Comment by rgolangh** [comment]
Anything to do on Renovate site, removing site details or so?

**Comment by imjoey** [comment]
I have uninstalled the renovatebot app from my github account and did not find any place to remove it from renovate site. Could you please open [Renovate App](https://github.com/apps/renovate) to see the installation status of renovate-bot and ensure that it is not installed for this project? Thanks.

**Comment by rgolangh** [comment]
I don't have it under my github account either.

**Comment by imjoey** [comment]
Could you please also check it under oVirt account? If no installed neither, I think nothing else that we need to do.

**Comment by rgolangh** [comment]
On Thu, 4 Jul 2019 at 18:16, Joey <notifications@github.com> wrote:

> Could you please also check it under oVirt account? If no installed
> neither, I think nothing else that we need to do.
>
>
I don't think there was someone that installed this app for ovirt so I
think you can go a head with this.

**Comment by imjoey** [comment]
OK. This PR is gonna be merged right now.  @rgolangh , thanks for your cooperation.

**Pull request merged**
