### PR TITLE
Fixes #377: Bug 1858418: ovirt_blank_template resource

### LINKED ISSUE #377: Add an `ovirt_blank_template` data source
## Please describe what you would like to see

We need a data source that dynamically looks up any available blank template ID.

## Please describe the solution you'd like

```terraform
data "ovirt_blank_template" "template" {
}

resource "ovirt_vm" "test" {
    template_id = ovirt_blank_template.template.id
}
```

## Please describe your use case

As described in [BZ 1858418](https://bugzilla.redhat.com/show_bug.cgi?id=1858418), users sometimes delete the blank template ID.

### PR DESCRIPTION
**Pull request by janosdebugs**
## Please describe the change you are making

This PR fixes #377 and [BZ 1858418](https://bugzilla.redhat.com/show_bug.cgi?id=1858418) by adding an `ovirt_blank_template` resource that returns the blank template ID.

## Are you the owner of the code you are sending in, or do you have permission of the owner?

Yes

## The code will be published under the BSD 3 clause license. Have you read and understood this license?

Yes

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Review by engelmi — APPROVED** [review]

**Pull request merged**
