### PR TITLE
Fixes #363: Add os_type parameter to ovirt_vm

### LINKED ISSUE #363: Add the `os_type` parameter to the `ovirt_vm` resource
## Please describe what you would like to see

Add the `os_type` parameter to the `ovirt_vm` resource.

### PR DESCRIPTION
**Pull request by janosdebugs**
## Please describe the change you are making

This PR adds the `os_type` parameter to the `ovirt_vm` resource.

## Are you the owner of the code you are sending in, or do you have permission of the owner?

Yes

## The code will be published under the BSD 3 clause license. Have you read and understood this license?

Yes

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Review by engelmi — APPROVED** [review]

**Pull request merged**
