### PR TITLE
ovirt_tag: if tag exists continue in resourceOvirtTagCreate

### PR DESCRIPTION
**Pull request by dougsland**
Changes proposed in this pull request:

If user try to use in terraform twice or more the statement:
resource "ovirt_tag" "cluster_tag" will raise error that
the tag already exists not allowing others vms to be tagged.
This patch detects if the tag exists and set the id from
the tag to the function continue without problem.

Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1806471
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1841380

Signed-off-by: Douglas Schilling Landgraf <dougsland@redhat.com>

Output from acceptance testing:
```
$ make testacc TEST=./ovirt TESTARGS='-run=TestAccOvirtDataCenter_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./ovirt -v -run=TestAccOvirtDataCenter_ -timeout 180m
=== RUN   TestAccOvirtDataCenter_basic
--- PASS: TestAccOvirtDataCenter_basic (1.04s)
PASS
ok  	github.com/ovirt/terraform-provider-ovirt/ovirt	(cached)
$ 
```

### CODE REVIEW

**Comment by dougsland** [comment]
@imjoey @rgolangh

**Comment by rgolangh** [comment]
Terraform either Creates or Updates or Deletes, and if you don't have a state set then terraform will try to create. It should always fail if such a resource already exist.

Instead of calling multiple times to a tag declaration, we can build a list of ids and pass it once, for example:
```
resource "ovirt_tag" "tag_bootstrap" {
  name   = "${var.cluster_id}-bootstrap"
  vm_ids = [concat(ovirt_vm.bootstrap.id, tmp_import_vm_id)]
}

I added more details on this comment - https://bugzilla.redhat.com/show_bug.cgi?id=1806471#c14

**Comment by dougsland** [comment]
> Terraform either Creates or Updates or Deletes, and if you don't have a state set then terraform
> will try to create. It should always fail if such a resource already exist.

Why update is not triggered than? 

> resource "ovirt_tag" "tag_bootstrap" {
>   name   = "${var.cluster_id}-bootstrap"
>   vm_ids = [concat(ovirt_vm.bootstrap.id, tmp_import_vm_id)]
> }

tmp_import_vm_id won't exist.

**Comment by dougsland** [comment]
@imjoey could you please help on the review too?

**Comment by rgolangh** [comment]
> Hey Roy,
> 
> Here a better feedback.
> 
> > Terraform either Creates or Updates or Deletes, and if you don't have a state set then terraform
> > will try to create. It should always fail if such a resource already exist.
> 
> I am wondering why the update is not triggered if it says the tag is already created? I can see in the tfstate file generated the tag in first place and later try to "create" the tag again. Probably , the file must exists to trigger the update?
> 
> > resource "ovirt_tag" "tag_bootstrap" {
> > name   = "${var.cluster_id}-bootstrap"
> > vm_ids = [concat(ovirt_vm.bootstrap.id, tmp_import_vm_id)]
> > }
> 
> Using code like:
> 
> ```
> installer/data/data/ovirt/bootstrap/main.tf
> +
> +resource "ovirt_tag" "cluster_bootstrap_tag" {
> +  name   = "${var.cluster_id}-bootstrap"
> +  vm_ids = concat([ovirt_vm.bootstrap.id], [var.ovirt_template_id])
> + }
> ```
> 
> This patch will create two tags like 'cluster-123' and other 'cluster-123-bootstrap'. In this case, we will need to change pkg/destroy/ovirt to also remove this new bootstrap tag and vms too.

Exactly. We already have code to remove the bootstrap vm exclusively. Now we will make that code bit more generic, to catch all bootstrap vm resources by the tag.

 Maybe we should still consider update the tag in case we try to "create the tag again" in the first run via tf?

Terraform only knows about state. If some entity is in the state file then any new declaration may(not always) update it. 
The installer only have a single step, the creation of resources. 

> It could help terraform users to support adding more than vm_id in the same tag.

what do you mean?

**Comment by dougsland** [comment]
> > Hey Roy,
> > Here a better feedback.
> > > Terraform either Creates or Updates or Deletes, and if you don't have a state set then terraform
> > > will try to create. It should always fail if such a resource already exist.
> > 
> > 
> > I am wondering why the update is not triggered if it says the tag is already created? I can see in the tfstate file generated the tag in first place and later try to "create" the tag again. Probably , the file must exists to trigger the update?
> > > resource "ovirt_tag" "tag_bootstrap" {
> > > name   = "${var.cluster_id}-bootstrap"
> > > vm_ids = [concat(ovirt_vm.bootstrap.id, tmp_import_vm_id)]
> > > }
> > 
> > 
> > Using code like:
> > ```
> > installer/data/data/ovirt/bootstrap/main.tf
> > +
> > +resource "ovirt_tag" "cluster_bootstrap_tag" {
> > +  name   = "${var.cluster_id}-bootstrap"
> > +  vm_ids = concat([ovirt_vm.bootstrap.id], [var.ovirt_template_id])
> > + }
> > ```
> > 
> > 
> > This patch will create two tags like 'cluster-123' and other 'cluster-123-bootstrap'. In this case, we will need to change pkg/destroy/ovirt to also remove this new bootstrap tag and vms too.
> 
> Exactly. We already have code to remove the bootstrap vm exclusively. Now we will make that code bit more generic, to catch all bootstrap vm resources by the tag.
> 
> Maybe we should still consider update the tag in case we try to "create the tag again" in the first run via tf?
> 
> Terraform only knows about state. If some entity is in the state file then any new declaration may(not always) update it.
> The installer only have a single step, the creation of resources.
> 
> > It could help terraform users to support adding more than vm_id in the same tag.
> 
> what do you mean?

@rgolangh 
terraform user set twice "ovirt_tag" "cluster_tag" because they want to tag two resources with the same tag.

**Comment by rgolangh** [comment]
use 2 different tags. one for 'cluster_tag' and one for 'bootstarp_tag'

**Comment by dougsland** [comment]
> > use 2 different tags. one for 'cluster_tag' and one for 'bootstarp_tag'
> 
> hey @rgolangh understood that but it won't solve the issue I have mentioned:
> 
> ```
> terraform user set twice "ovirt_tag" "cluster_tag" because they want to tag two resources with the same tag.
> ```

@rgolangh ping. We still cannot use the same tag in the terraform deploy.

**Comment by dougsland** [comment]
Closing in favor of: https://github.com/openshift/installer/pull/3868

**Pull request closed without merging**
