### PR TITLE
Update the dependecy of oVirt Go SDK to v4.3.5

### PR DESCRIPTION
**Pull request by imjoey**
Signed-off-by: imjoey <majunjiev@gmail.com>

Changes proposed in this pull request:

* Update oVirt Go SDK to the latest `v4.3.5`, along with relevant vendor files

### CODE REVIEW

**Comment by llomgui** [comment]
Hello,

Renovate bot is supposed to update it itself. I think it's broken with the migration to oVirt.

**Comment by imjoey** [comment]
hi @llomgui , you are right. I will close this draft PR once Renovate bot is re-enabled.

hi @rgolangh , shall we continue using Renovate bot to manage dependencies automatically? Please let us know your opinion. Thanks.

**Comment by imjoey** [comment]
> hi @rgolangh , shall we continue using Renovate bot to manage dependencies automatically? Please let us know your opinion. Thanks.

Hi @rgolangh , we are looking forward to your opinion about Renovate bot, as installing the Renovate bot requires the oVirt organization write permissions. Thank you.

**Comment by rgolangh** [comment]
Do we have to have the deps updates so frequently?

**Comment by imjoey** [comment]
> Do we have to have the deps updates so frequently?

Not really, I think. While Renovate bot could still relieve us from the workloads of deps management. We could just close the pull request from renovate-bot if we don't want to update. In addition, from my viewpoint, what Renovate bot help us most is that it could continually remind us the latest version of  any dep that we won't miss any significant or incompatible changes. What's your insights on this? Thanks.

**Comment by rgolangh** [comment]
The tradeoff will we features with stability. What are missing mostly from
our dependencies -  features, security fixes?

If we pick stability, and we set the versions to stable version, renovate
will post PR whenever there will be an update of a stable version?

**Comment by imjoey** [comment]
> The tradeoff will we features with stability. What are missing mostly from our dependencies - features, security fixes? If we pick stability, and we set the versions to stable version, renovate will post PR whenever there will be an update of a stable version?

The stability is and will be always the most important for us. :) Although renovate would post a PR for any version update, it still depends on us to recognize whether it's a stable version and worthy of merged. At least, it could remind us there is a new version in case we miss all updates for quite a long time.

After some digs, I found that the aws-provider is using renovate while openstack-provider is not. So in practice, either is OK. Probably what we are concerning most is how to judge a new version is stable and it should be merged. For example, this PR is going to update Go SDK to v4.3.5. Compared with v4.3.4, the new v4.3.5 only contain some tiny features such as new parameters or new functions, but none of these new things are relevant to the existing functionality of terraform provider. Could you please let me know what's your opinion about whether this PR could be merged? Thank you very much. 😄

**Comment by imjoey** [comment]
Hi @rgolangh , today I had discussions with many of my workmates. Nearly 3/4 of them choose manually managing deps rather than using renovate. They also think this PR should not be merged since it brings no benefit to currently project. I think I've been persuaded that we should keep the project stable and simple, not annoyed by unexpected PRs by renovate.

I would close this PR now and also post another PR to remove current `renovate.json`.  I'm so grateful to take the discussions with you. Thank you very much.

**Comment by imjoey** [comment]
Hi @llomgui , really thanks for your attentions and hopefully you could understand why we make this final decision. Please keep on with your contributions. Thanks. 😄

**Comment by rgolangh** [comment]
@imjoey  Glad the discussion are fruitful - and thanks for keeping it open

**Pull request closed without merging**
