### PR TITLE
Fixes #347: graphics consoles handling

### LINKED ISSUE #347: Implement the `ovirt_vm_graphic_consoles` resource
## Please describe what you would like to see

We need a way to remove all graphics consoles from a VM after creation.

## Please describe the solution you'd like

In keeping with Terraform semantics, we need a resource that manages graphics consoles on a VM:

```terraform
resource "ovirt_vm_graphic_consoles" "master" {
  vm_id = var.vm_id
  graphics_console {
    // Graphics console parameters
  }
  graphics_console {
    // Graphics console parameters
  }
}
```

However, at this time it is enough if we support exactly 0 graphics consoles as we only need to remove them. 

## Please describe your use case

We need to remove all graphics consoles from a VM for high performance.

### PR DESCRIPTION
**Pull request by janosdebugs**
## Please describe the change you are making

This PR adds support for removing graphics consoles from a VM (#347). It depends on ovirt/go-ovirt-client#192

## Are you the owner of the code you are sending in, or do you have permission of the owner?

Yes

## The code will be published under the BSD 3 clause license. Have you read and understood this license?

Yes

### CODE REVIEW

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Comment by ovirt-infra** [comment]
All tests passed

**Review by engelmi — APPROVED** [review]

**Pull request merged**
